filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata: ~
